// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskPlanner.Persistence.Contexts;

#nullable disable

namespace TaskPlanner.Persistence.Migrations.MVPTestDatabase
{
    [DbContext(typeof(MVPTestDatabaseContext))]
    [Migration("20250826121218_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.FavoriteOutfitStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserId", "OutfitStyleId")
                        .IsUnique();

                    b.ToTable("FavoriteOutfitStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutfitStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.TryOnHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<string>("OutputUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserPhotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UserPhotoId", "OutfitStyleId", "CreatedAt");

                    b.ToTable("TryOnHistories");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPhotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserPhotoId");

                    b.ToTable("UserStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<int>("UserStyleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserStyleId");

                    b.ToTable("UserStyleItems");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.FavoriteOutfitStyle", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutfitStyle");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", "UserPhoto")
                        .WithMany()
                        .HasForeignKey("UserPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserPhoto");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyleItem", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", "UserStyle")
                        .WithMany("Items")
                        .HasForeignKey("UserStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutfitStyle");

                    b.Navigation("UserStyle");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
