// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskPlanner.Persistence.Contexts;

#nullable disable

namespace TaskPlanner.Persistence.Migrations.MVPTestDatabase
{
    [DbContext(typeof(MVPTestDatabaseContext))]
    [Migration("20251001144142_Add-User_correction4")]
    partial class AddUser_correction4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.FavoriteOutfitStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserId", "OutfitStyleId")
                        .IsUnique();

                    b.ToTable("FavoriteOutfitStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutfitStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.TryOnHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<string>("ResultUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserPhotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserPhotoId");

                    b.HasIndex("UserId", "UserPhotoId", "OutfitStyleId", "CreatedAt");

                    b.ToTable("TryOnHistories");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPhotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserPhotoId");

                    b.ToTable("UserStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<int>("UserStyleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserStyleId");

                    b.ToTable("UserStyleItems");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskCategory");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItem");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Age")
                        .HasColumnType("datetime2");

                    b.Property<int?>("City")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Documents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCentralOffice")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemove")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVarify")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("Province")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.FavoriteOutfitStyle", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutfitStyle");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.TryOnHistory", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", "UserPhoto")
                        .WithMany("Histories")
                        .HasForeignKey("UserPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OutfitStyle");

                    b.Navigation("UserPhoto");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", "UserPhoto")
                        .WithMany()
                        .HasForeignKey("UserPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserPhoto");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyleItem", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", "UserStyle")
                        .WithMany("Items")
                        .HasForeignKey("UserStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutfitStyle");

                    b.Navigation("UserStyle");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.Users.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.ProjectMember", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabloyar.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.Users.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskCategory", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", "Parent")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Category");

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", b =>
                {
                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
