// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskPlanner.Persistence.Contexts;

#nullable disable

namespace TaskPlanner.Persistence.Migrations.MVPTestDatabase
{
    [DbContext(typeof(MVPTestDatabaseContext))]
    [Migration("20251005055658_ProjectInvitation_Correction")]
    partial class ProjectInvitation_Correction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.FavoriteOutfitStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserId", "OutfitStyleId")
                        .IsUnique();

                    b.ToTable("FavoriteOutfitStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutfitStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.TryOnHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<string>("ResultUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserPhotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserPhotoId");

                    b.HasIndex("UserId", "UserPhotoId", "OutfitStyleId", "CreatedAt");

                    b.ToTable("TryOnHistories");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPhotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserPhotoId");

                    b.ToTable("UserStyles");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OutfitStyleId")
                        .HasColumnType("int");

                    b.Property<int>("UserStyleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutfitStyleId");

                    b.HasIndex("UserStyleId");

                    b.ToTable("UserStyleItems");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.ProjectInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InviteeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InviteePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InviterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "InviteeId", "Status");

                    b.ToTable("ProjectInvitations");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.FavoriteOutfitStyle", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutfitStyle");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.TryOnHistory", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", "UserPhoto")
                        .WithMany("Histories")
                        .HasForeignKey("UserPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OutfitStyle");

                    b.Navigation("UserPhoto");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", "UserPhoto")
                        .WithMany()
                        .HasForeignKey("UserPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserPhoto");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyleItem", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.OutfitStyle", "OutfitStyle")
                        .WithMany()
                        .HasForeignKey("OutfitStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", "UserStyle")
                        .WithMany("Items")
                        .HasForeignKey("UserStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutfitStyle");

                    b.Navigation("UserStyle");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.ProjectInvitation", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.ProjectMember", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", b =>
                {
                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskCategory", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", "Parent")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserPhoto", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.OutfitTryOn.UserStyle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Tabloyar.Domain.Entities.AdditionalEntity.TaskPlanner.TaskItem", b =>
                {
                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
