# =====================================================================
# اسکریپت ساخت بسته (bundle) CSS
# =====================================================================
# هر بار که یکی از فایل‌های CSS زیر را تغییر دادید، این اسکریپت را اجرا کنید:
#   pwsh ./build-css-bundle.ps1
# یا در PowerShell:
#   .\build-css-bundle.ps1
# =====================================================================

$ErrorActionPreference = "Stop"

$cssDir = Join-Path $PSScriptRoot "wwwroot/css"

# ترتیب مهم است: ابتدا متغیرها/پایه، بعد لایه‌ها
$sources = @(
    "site.css",
    "app-shell.css",
    "project-sidebar.css"
)
# توجه: ChatBox.css و projects-index.css در bundle نیستند چون فقط در صفحات خاص لازم‌اند

$outFile = Join-Path $cssDir "app-bundle.css"

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("/* ============================================================ */")
[void]$sb.AppendLine("/*  AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY                  */")
[void]$sb.AppendLine("/*  Generated by build-css-bundle.ps1                            */")
[void]$sb.AppendLine("/*  Source files: $($sources -join ', ')                         */")
[void]$sb.AppendLine("/* ============================================================ */")
[void]$sb.AppendLine("")

foreach ($src in $sources) {
    $path = Join-Path $cssDir $src
    if (-not (Test-Path $path)) {
        Write-Error "Source file not found: $path"
        exit 1
    }
    [void]$sb.AppendLine("/* ===== $src ===== */")
    [void]$sb.AppendLine((Get-Content $path -Raw))
    [void]$sb.AppendLine("")
}

# minify ساده: حذف کامنت‌های /* ... */ (به جز خط اول هدر)، حذف خطوط خالی متعدد و فضاهای اضافه
$content = $sb.ToString()

# جلوگیری از حذف هدر — موقتا جدا می‌کنیم
$headerEnd = $content.IndexOf("*/", 0) + 2
$header = $content.Substring(0, $headerEnd)
$body = $content.Substring($headerEnd)

# حذف کامنت‌های CSS از body
$body = [System.Text.RegularExpressions.Regex]::Replace($body, "/\*[\s\S]*?\*/", "")
# حذف فضاهای اضافه پشت/جلوی کاراکترهای خاص
$body = [System.Text.RegularExpressions.Regex]::Replace($body, "\s*([{};:,])\s*", '$1')
# حذف ; قبل از }
$body = $body -replace ";}", "}"
# حذف خطوط خالی متعدد
$body = [System.Text.RegularExpressions.Regex]::Replace($body, "\n\s*\n", "`n")

$final = $header + "`n" + $body.Trim()

Set-Content -Path $outFile -Value $final -Encoding UTF8

$origSize = ($sources | ForEach-Object { (Get-Item (Join-Path $cssDir $_)).Length } | Measure-Object -Sum).Sum
$newSize = (Get-Item $outFile).Length
$reduction = [math]::Round((1 - $newSize / $origSize) * 100, 1)

Write-Host "✔ Bundle created: $outFile" -ForegroundColor Green
Write-Host "  Original: $([math]::Round($origSize/1024,2)) KB"
Write-Host "  Bundle:   $([math]::Round($newSize/1024,2)) KB  (-$reduction%)" -ForegroundColor Cyan
