<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DNTPersianUtils.Core" Version="6.7.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskPlanner.Application\TaskPlanner.Application.csproj" />
    <ProjectReference Include="..\TaskPlanner.Infrastructure\TaskPlanner.Infrastructure.csproj" />
    <ProjectReference Include="..\TaskPlanner.Persistence\TaskPlanner.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Models\AdminViewModel\" />
    <Folder Include="wwwroot\uploads\" />
    <Folder Include="wwwroot\uploads\personal-notes\" />
    <Folder Include="wwwroot\uploads\project-notes\" />
  </ItemGroup>

</Project>
